fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.6.0'
    augeas:
      repo: 'https://github.com/puppetlabs/puppetlabs-augeas_core.git'
      ref: '1.0.4'
  symlinks:
    smartd: "#{source_dir}"
