sudo: false
language: ruby
bundler_args: --without beaker
matrix:
  include:
    - rvm: 2.0
      env: PUPPET_GEM_VERSION="~> 3.7"
    - rvm: 2.1
      env: PUPPET_GEM_VERSION="~> 3.7"
    - rvm: 2.1
      env: PUPPET_GEM_VERSION="~> 4.0"
    - rvm: 2.4
      env: PUPPET_GEM_VERSION="~> 5.0"
    - rvm: 2.5
      env: PUPPET_GEM_VERSION="~> 6.0"
  fast_finish: true
notifications:
  email: false
